OK JEU CHARGEMENT MATRICE INITIALE A 0

In [1]:
import numpy as np
n = 4
grid = np.zeros ((n,n), dtype = int)
print (grid)
print ("Python affecte le type suivant à grid : ", type(grid))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Python affecte le type suivant à grid :  <class 'numpy.ndarray'>


OK JEU CHOIX DE LA VALEUR A CHARGER AVANT JEU AVEC 1 CASE A 2 OU 4  PROBA 80 % ET 20%

In [2]:
import numpy as np
n = 4
grid = np.zeros ((n,n), dtype = int)
row = np.random.choice ([0,1,2,3],2, replace = False)
col = np.random.choice ([0,1,2,3],2)
print ("Positions d'affectation des 2 valeurs de départ", "rows :", row, "columns :", col)


Positions d'affectation des 2 valeurs de départ rows : [3 1] columns : [0 2]


OK JEU CHOIX DE LA POSITION D'INSERTION DE LA MATRICE INITIALISEE

In [3]:
import numpy as np
n = 4
value = np.random.choice ([2,4],2, replace = True, p = [0.8,0.2])
print ("Valeurs aléatoires tirées :", value)

Valeurs aléatoires tirées : [2 2]


OK JEU RESTITUTION MATRICE INIT CHARGEE

In [4]:
import numpy as np
n = 4
def init_grid (n):
    grid = np.zeros ((n,n), dtype = int)
    row = np.random.choice ([0,1,2,3],2, replace = False)
    col = np.random.choice ([0,1,2,3],2)
    value = np.random.choice ([2,4],2, replace = True, p = [0.8,0.2])
    grid [row[0],col[0]] = value[0]
    grid [row[1],col[1]] = value[1]
    print (row , type(row))
    print (col, type(col))
    print (value, type (value))
    return grid
print (init_grid(n))

[1 2] <class 'numpy.ndarray'>
[0 3] <class 'numpy.ndarray'>
[4 2] <class 'numpy.ndarray'>
[[0 0 0 0]
 [4 0 0 0]
 [0 0 0 2]
 [0 0 0 0]]


OK JEU EN CAS DE MVT UP/DOWN/LEFT/RIGHT a- ajout d'un 2 ou un 4 dans une case vide si case vide (80%/ 20%)

In [67]:
import numpy as np
n = 4
a = np.zeros ((n,n), dtype = int)
r = np.random.choice ([0,1,2,3],2, replace = False)
c = np.random.choice ([0,1,2,3],2)
v = np.random.choice ([2,4],2, replace = True, p = [0.8,0.2])
a [r[0],c[0]] = v[0]
a [r[1],c[1]] = v[1]
print (a)
result = (np.where(a==0))
listCoordinates= list(zip(result[0], result[1]))
if listCoordinates != 0:
    print (listCoordinates)
    element_list = np.random.randint (0,len(listCoordinates), dtype = int)
    print (element_list)
    v = np.random.choice ([2,4], p = [0.8,0.2])
    a [listCoordinates [element_list-1]] = v
print (a)


[[0 0 4 0]
 [0 0 0 0]
 [0 0 0 0]
 [2 0 0 0]]
[(0, 0), (0, 1), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3)]
1
[[2 0 4 0]
 [0 0 0 0]
 [0 0 0 0]
 [2 0 0 0]]


In [30]:
import numpy as np
grid2 = []
n = 4
grid2 = np.array ([[4, 4, 4, 4], [0, 0, 0, 0],[2, 2, 2, 2],[2, 2, 2, 2]])
print (grid2, "grid initiale", "\n") # suppression des 0 et décalage des cases remplies vers le haut toutes lignes/1 colonne
c=0
for l in range (0,3):
    w = l 
    if grid2 [l, c] == 0 and w <= 3:
            print ("valeur l", l,"valeur w", w )
            while w < 3 and grid2 [w,c] == 0:
                w = w + 1    
            grid2 [l,c] = grid2 [w,c]
            grid2 [w,c] = 0
print (grid2, "grid apres tassement initial", "\n")

[[4 4 4 4]
 [0 0 0 0]
 [2 2 2 2]
 [2 2 2 2]] grid initiale 

valeur l 1 valeur w 1
valeur l 2 valeur w 2
[[4 4 4 4]
 [2 0 0 0]
 [2 2 2 2]
 [0 2 2 2]] grid apres tassement initial 



In [31]:
import numpy as np
grid2 = []
n = 4
grid2 = np.array ([[4, 4, 4, 0], [0, 0, 0, 0],[2, 2, 2, 2],[2, 2, 2, 2]])
print (grid2, "grid initiale", "\n") # suppression des 0 et décalage des cases vers le haut, toutes lignes et colonnes
for c in range (0,4):
    for l in range (0,3):
        w = l 
        if grid2 [l, c] == 0 and w <= 3:
            while w < 3 and grid2 [w,c] == 0:
                w = w + 1    
            grid2 [l,c] = grid2 [w,c]
            grid2 [w,c] = 0
    print (grid2, "grid apres tassement initial", "\n")

[[4 4 4 0]
 [0 0 0 0]
 [2 2 2 2]
 [2 2 2 2]] grid initiale 

[[4 4 4 0]
 [2 0 0 0]
 [2 2 2 2]
 [0 2 2 2]] grid apres tassement initial 

[[4 4 4 0]
 [2 2 0 0]
 [2 2 2 2]
 [0 0 2 2]] grid apres tassement initial 

[[4 4 4 0]
 [2 2 2 0]
 [2 2 2 2]
 [0 0 0 2]] grid apres tassement initial 

[[4 4 4 2]
 [2 2 2 2]
 [2 2 2 0]
 [0 0 0 0]] grid apres tassement initial 



In [32]:
import numpy as np
grid2 = []
n = 4
grid = np.array ([[0, 0, 0, 0], [0, 0, 0, 0],[2, 2, 2, 0],[2, 2, 2, 2]])
print (grid, "grid initiale", "\n") # supp 0 + décal vers le haut à partir de l, 1 colonne, via fonction
line = 0
def decal_line (grid,line,col):
    for i in range (line,3):
        w = i
        if grid [i, col] == 0 and w <= 3:
            while w < 3 and grid [w,col] == 0:
                w = w + 1    
            print ("w et  i et col valent ", w, i,col)
            grid [i,col] = grid [w,col]
            grid [w,col] = 0
    print (grid, "grid apres tassement ", "\n")
    return (grid)
decal_line (grid,0,3)


[[0 0 0 0]
 [0 0 0 0]
 [2 2 2 0]
 [2 2 2 2]] grid initiale 

w et  i et col valent  3 0 3
w et  i et col valent  3 1 3
w et  i et col valent  3 2 3
[[0 0 0 2]
 [0 0 0 0]
 [2 2 2 0]
 [2 2 2 0]] grid apres tassement  



array([[0, 0, 0, 2],
       [0, 0, 0, 0],
       [2, 2, 2, 0],
       [2, 2, 2, 0]])

VERSION OK POUR NETTOYER LES 0 A PARTIR D'UNE LIGNE DEFINIE VIA UNE FONCTION :

In [37]:
import numpy as np
grid2 = []
n = 4
grid = np.array ([[0, 0, 0, 0], [0, 0, 0, 0],[2, 2, 2, 0],[2, 2, 2, 2]])
print (grid, "grid initiale", "\n") # supp 0 + décal vers le haut à partir de l, 1 colonne, via fonction
line = 0
def decal_line (grid,line,col):
    for i in range (line,3):
        w = i
        if grid [i, col] == 0 and w <= 3:
            while w < 3 and grid [w,col] == 0:
                w = w + 1    
            grid [i,col] = grid [w,col]
            grid [w,col] = 0
    return (grid)
line = 0
for col in range (0,4): # décalage de ligne à partir de line=x sur chaque colonne pour retrait des 0
    decal_line (grid,line,col)
print (grid)


[[0 0 0 0]
 [0 0 0 0]
 [2 2 2 0]
 [2 2 2 2]] grid initiale 

[[2 2 2 2]
 [2 2 2 0]
 [0 0 0 0]
 [0 0 0 0]]


VERSION OK POUR CUMULER les cases et NETTOYER LES 0 A PARTIR si touche "UP"  :

In [49]:
import numpy as np
n = 4
grid = np.array ([[0, 2, 4, 0], [0, 2, 2, 0],[2, 2, 2, 0],[2, 2, 2, 2]])
print (grid, "grid initiale", "\n") # supp 0+cumul+decal vers le haut à partir de l, ttes colonnes, via fonction
line = 0
def decal_line (grid,line,col):
    for i in range (line,3):
        w = i
        if grid [i, col] == 0 and w <= 3:
            while w < 3 and grid [w,col] == 0:
                w = w + 1    
            grid [i,col] = grid [w,col]
            grid [w,col] = 0
    return (grid)
for col in range (0,4): # ajout 2 par 2 et decal 
    for line in range (0,3):
        if grid [line,col] == 0:
            decal_line (grid,line, col)
        if grid [line,col] != 0 and grid [line+1,col] == 0:
            decal_line(grid, line+1, col)   
        if grid [line,col] == grid [line+1,col] and grid [line,col] != 0 and line < 3:
            grid [line,col] += grid [line+1, col]
            grid [line+1,col] = 0
print (grid, " apres ajout de ligne identiques")

[[0 2 4 0]
 [0 2 2 0]
 [2 2 2 0]
 [2 2 2 2]] grid initiale 

[[4 4 4 2]
 [0 4 4 0]
 [0 0 2 0]
 [0 0 0 0]]  apres ajout de ligne identiques
[[2 0 0 0]
 [4 4 2 0]
 [4 4 0 0]
 [4 0 0 0]]  rotation 90


VERSION OK JEU avec les 4 MOUVEMENTS POSSIBLES OK : TOUT MVT hors UP est un UP APRES ROTATION/MVT/ROTATION 

A CONNAITRE 
rotation de matrice grid = np.rot90 (grid,2) : 2 rotations de 90 = 180 en unclockwise

récuperer ou charger la diagonale d'une matrice : grid = np.diag (grid)

np.all(grid [1,:] ==1) : booléen verifie la presence de "1" sur tous les cases de la ligne 1, renvoie True ou False
np.all(grid [:,0] ==0) : booléen verifie la presence de "0" sur tous les cases de la colonne 0, renvoie True ou False
np.all(grid [:,:] == 0)

In [9]:
import numpy as np
n = 4
grid = np.array ([[0, 2, 4, 0], [0, 2, 2, 0],[2, 2, 2, 0],[2, 2, 2, 2]])
print (grid, "grid initiale", "\n") # supp 0+cumul+decal vers le haut à partir de l, ttes colonnes, via fonctions
line = 0
def decal_line (grid,line,col):
    for i in range (line,3):
        w = i
        if grid [i, col] == 0 and w <= 3:
            while w < 3 and grid [w,col] == 0:
                w = w + 1    
            grid [i,col] = grid [w,col]
            grid [w,col] = 0
    return (grid)
def moove_up (grid): # ajout 2 par 2 et decal 
    for col in range (0,4): 
        for line in range (0,3):
            if grid [line,col] == 0:
                decal_line (grid,line, col)
            if grid [line,col] != 0 and grid [line+1,col] == 0:
                decal_line(grid, line+1, col)   
            if grid [line,col] == grid [line+1,col] and grid [line,col] != 0 and line < 3:
                grid [line,col] += grid [line+1, col]
                grid [line+1,col] = 0
    print (grid, 'apres additions suite mvt UP', "\n")
    return (grid)
moove = "right"
if moove == "up":
    moove_up (grid)
if moove == "down":
    grid = np.rot90 (grid,2)
    moove_up (grid)
    grid = np.rot90 (grid,2)
if moove == "right":
    grid = np.rot90 (grid,1)
    moove_up (grid)
    grid = np.rot90 (grid,3)
if moove == "left":
    grid = np.rot90 (grid,3)
    moove_up (grid)
    grid = np.rot90 (grid)
print (grid, "aprè mvt ", moove, "\n")
print (np.all (grid[1,:]== 1),"analyse de la ligne1", "\n")
print (np.all (grid[:,0]== 0),"analyse de la colonne 0" "\n")
grid2 = np.zeros ((n,n), dtype = int)
print (np.all (grid2[:,:]== 0),"analyse de toute la matrice a valeur 0" "\n")
print (np.diag (grid), "\n")




[[0 2 4 0]
 [0 2 2 0]
 [2 2 2 0]
 [2 2 2 2]] grid initiale 

[[4 4 4 4]
 [2 0 2 4]
 [0 0 0 0]
 [0 0 0 0]] apres additions suite mvt UP 

[[0 0 2 4]
 [0 0 0 4]
 [0 0 2 4]
 [0 0 4 4]] aprè mvt  right 

False analyse de la ligne1 

True analyse de la colonne 0

True analyse de toute la matrice a valeur 0

[0 0 2 4] 

